param(
	[string]$OutputPath = "dist/TailUI.executor.lua"
)

$ErrorActionPreference = "Stop"

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

$modules = @(
	@{ Name = "Core.Logger"; Path = "src/Core/Logger.lua" },
	@{ Name = "Core.SafeCall"; Path = "src/Core/SafeCall.lua" },
	@{ Name = "Core.FileSystem"; Path = "src/Core/FileSystem.lua" },
	@{ Name = "Core.ConfigManager"; Path = "src/Core/ConfigManager.lua" },
	@{ Name = "Theme.BuiltinThemes"; Path = "src/Theme/BuiltinThemes.lua" },
	@{ Name = "Theme.ThemeManager"; Path = "src/Theme/ThemeManager.lua" },
	@{ Name = "Assets.IconRegistry"; Path = "src/Assets/IconRegistry.lua" },
	@{ Name = "Assets.FontRegistry"; Path = "src/Assets/FontRegistry.lua" },
	@{ Name = "UI.FuzzySearch"; Path = "src/UI/FuzzySearch.lua" },
	@{ Name = "UI.LoadingOverlay"; Path = "src/UI/LoadingOverlay.lua" },
	@{ Name = "UI.Window"; Path = "src/UI/Window.lua" },
	@{ Name = "TailUI"; Path = "src/TailUI.lua" }
)

function Transform-Module {
	param(
		[string]$Name,
		[string]$Code
	)

	if ($Name -eq "UI.Window") {
		$Code = $Code -replace 'local FuzzySearch = require\(script\.Parent\.FuzzySearch\)', 'local FuzzySearch = __require("UI.FuzzySearch")'
		$Code = $Code -replace 'local LoadingOverlay = require\(script\.Parent\.LoadingOverlay\)', 'local LoadingOverlay = __require("UI.LoadingOverlay")'
	}

	if ($Name -eq "TailUI") {
		$Code = $Code -replace 'local Logger = require\(script\.Core\.Logger\)', 'local Logger = __require("Core.Logger")'
		$Code = $Code -replace 'local SafeCall = require\(script\.Core\.SafeCall\)', 'local SafeCall = __require("Core.SafeCall")'
		$Code = $Code -replace 'local FileSystem = require\(script\.Core\.FileSystem\)', 'local FileSystem = __require("Core.FileSystem")'
		$Code = $Code -replace 'local ConfigManager = require\(script\.Core\.ConfigManager\)', 'local ConfigManager = __require("Core.ConfigManager")'
		$Code = $Code -replace 'local ThemeManager = require\(script\.Theme\.ThemeManager\)', 'local ThemeManager = __require("Theme.ThemeManager")'
		$Code = $Code -replace 'local BuiltinThemes = require\(script\.Theme\.BuiltinThemes\)', 'local BuiltinThemes = __require("Theme.BuiltinThemes")'
		$Code = $Code -replace 'local IconRegistry = require\(script\.Assets\.IconRegistry\)', 'local IconRegistry = __require("Assets.IconRegistry")'
		$Code = $Code -replace 'local FontRegistry = require\(script\.Assets\.FontRegistry\)', 'local FontRegistry = __require("Assets.FontRegistry")'
		$Code = $Code -replace 'local Window = require\(script\.UI\.Window\)', 'local Window = __require("UI.Window")'
	}

	return $Code
}

$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine("-- Tail UI Library Executor Bundle")
[void]$sb.AppendLine("-- Generated by tools/build_executor_bundle.ps1")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("local __modules = {}")
[void]$sb.AppendLine("local __cache = {}")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("local function __require(name)")
[void]$sb.AppendLine("	local cached = __cache[name]")
[void]$sb.AppendLine("	if cached ~= nil then")
[void]$sb.AppendLine("		return cached")
[void]$sb.AppendLine("	end")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("	local loader = __modules[name]")
[void]$sb.AppendLine("	if not loader then")
[void]$sb.AppendLine("		error(""[TailUI Bundle] module not found: "" .. tostring(name), 2)")
[void]$sb.AppendLine("	end")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("	local value = loader()")
[void]$sb.AppendLine("	__cache[name] = value")
[void]$sb.AppendLine("	return value")
[void]$sb.AppendLine("end")
[void]$sb.AppendLine("")

foreach ($module in $modules) {
	$modulePath = Join-Path $root $module.Path
	$code = Get-Content -Raw -Path $modulePath
	$code = Transform-Module -Name $module.Name -Code $code

	[void]$sb.AppendLine(("__modules[""{0}""] = function()" -f $module.Name))
	[void]$sb.AppendLine($code.TrimEnd())
	[void]$sb.AppendLine("end")
	[void]$sb.AppendLine("")
}

[void]$sb.AppendLine("local __old_tail_require = _G.__TAILUI_REQUIRE")
[void]$sb.AppendLine("_G.__TAILUI_REQUIRE = __require")
[void]$sb.AppendLine("local __tail_value = __require(""TailUI"")")
[void]$sb.AppendLine("if __old_tail_require == nil then")
[void]$sb.AppendLine("	_G.__TAILUI_REQUIRE = nil")
[void]$sb.AppendLine("else")
[void]$sb.AppendLine("	_G.__TAILUI_REQUIRE = __old_tail_require")
[void]$sb.AppendLine("end")
[void]$sb.AppendLine("return __tail_value")

$outputFullPath = Join-Path $root $OutputPath
$outputDir = Split-Path -Parent $outputFullPath
if (-not (Test-Path $outputDir)) {
	New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$sb.ToString() | Set-Content -Path $outputFullPath -NoNewline
Write-Host "Bundle generated at: $outputFullPath"
